server:
  port: 9099
#  servlet:
#    context-path: /eureka   #这里不能和serviceUrl最后的路径完全一样，否则client不能注册进来
eureka:
  instance:
    hostname: eureka-server
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
