server:
  port: 9020
spring:
  application:
    name: config-server
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xiaochangwei/spring-cloud-summarize/
          search-paths: /spring-cloud-config-server/config
      label: master
#        native:
#          search-locations: fileD:\codes\spring-cloud-summarize\spring-cloud-config-server\src\main\resources\config
#  profiles:
#    active: native
#        git:
#          uri: https://github.com/xiaochangwei/spring-cloud-summarize.git
#          search-paths: /spring-cloud-config-server/src/main/resources/config
###################### eureka ###########################
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://admin:123456@127.0.0.1:9090/eureka
#      defaultZone: http://127.0.0.1:9091/eureka,http://127.0.0.1:9092/eureka,http://127.0.0.1:9093/eureka
    registry-fetch-interval-seconds: 1 #从Eureka服务器获取注册信息间隔时间 默认 30s
  instance:
    lease-renewal-interval-in-seconds: 1 #租期更新时间间隔 默认 30s
    lease-expiration-duration-in-seconds: 5 #租期到期时间 默认 90s #经测试，注册中心清理时间为该值*2（清理间隔为1s情况下）

